# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.50321267, 0.15958234, 0.95112341, 0.41712892, 0.371625  ],
        [0.09869274, 0.23475594, 0.87357604, 0.05684885, 0.65809426],
        [0.43992422, 0.59552003, 0.16227868, 0.97770196, 0.37988525]],

       [[0.82373042, 0.63296602, 0.28812709, 0.97850435, 0.95257943],
        [0.72461   , 0.98032832, 0.31917599, 0.33005618, 0.30508572],
        [0.66363754, 0.84819495, 0.05430705, 0.24175206, 0.67473159]]])

In [5]:
# Method 2
c = np.arange(30).reshape(2,3,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [6]:
# Method 3
d= np.random.rand(2,3,5)
d

array([[[0.3318188 , 0.54681295, 0.36737747, 0.61823271, 0.2899149 ],
        [0.01350761, 0.18921492, 0.77024136, 0.13277236, 0.63647445],
        [0.47862829, 0.43014318, 0.12683262, 0.42532714, 0.51670787]],

       [[0.13772769, 0.70673607, 0.19006641, 0.74833252, 0.33501849],
        [0.79609201, 0.20390816, 0.72426248, 0.68106466, 0.9576266 ],
        [0.10028584, 0.54108534, 0.54958985, 0.67490768, 0.5848433 ]]])

#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.50321267 0.15958234 0.95112341 0.41712892 0.371625  ]
  [0.09869274 0.23475594 0.87357604 0.05684885 0.65809426]
  [0.43992422 0.59552003 0.16227868 0.97770196 0.37988525]]

 [[0.82373042 0.63296602 0.28812709 0.97850435 0.95257943]
  [0.72461    0.98032832 0.31917599 0.33005618 0.30508572]
  [0.66363754 0.84819495 0.05430705 0.24175206 0.67473159]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here
b=np.ones((5,2,3),dtype=int)


#### 6. Print *b*.


In [12]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
# your code here
#n=3
#def matrix_check(a,b):
#    for i in range(n):
#        for j in range(n):
#            if (a[i][j] != b[i][j]):
#                return 0
#    return 1
#if (matrix_check(a,b)==1):
#    print("matrices are identical")
#else:
#    print("matrices are not identical")


matrices are not identical


C:\Users\leandro\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


In [18]:
row1 = len(a);  
col1 = len(a[0])  
row2 = len(b)  
col2 = len(b[0])  
if(row1 != row2 or col1 != col2):  
    print("Matrices are not equal");  
   
else:  
    for i in range(0, row1):  
        for j in range(0, col1):  
            if(a[i][j] != b[i][j]):  
                flag = False;  
                break;  
      
    if(flag):  
        print("Matrices are equal");  
    else:  
        print("Matrices are not equal");  

Matrices are not equal


#### 8. Are you able to add *a* and *b*? Why or why not?


In [34]:
# your answer here
amatrix=a.__add__(b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [33]:
# your code here
c=b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
d=a.__add__(c)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
# your code/answer here
print(a)
print("\n")
print(d)

[[[0.50321267 0.15958234 0.95112341 0.41712892 0.371625  ]
  [0.09869274 0.23475594 0.87357604 0.05684885 0.65809426]
  [0.43992422 0.59552003 0.16227868 0.97770196 0.37988525]]

 [[0.82373042 0.63296602 0.28812709 0.97850435 0.95257943]
  [0.72461    0.98032832 0.31917599 0.33005618 0.30508572]
  [0.66363754 0.84819495 0.05430705 0.24175206 0.67473159]]]


[[[1.50321267 1.15958234 1.95112341 1.41712892 1.371625  ]
  [1.09869274 1.23475594 1.87357604 1.05684885 1.65809426]
  [1.43992422 1.59552003 1.16227868 1.97770196 1.37988525]]

 [[1.82373042 1.63296602 1.28812709 1.97850435 1.95257943]
  [1.72461    1.98032832 1.31917599 1.33005618 1.30508572]
  [1.66363754 1.84819495 1.05430705 1.24175206 1.67473159]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [43]:
# your code here
e=a.dot(c)

ValueError: shapes (2,3,5) and (2,3,5) not aligned: 5 (dim 2) != 3 (dim 1)

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# no: shapes (2,3,5) and (2,3,5) not aligned: 5 (dim 2) != 3 (dim 1)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [88]:
# your code here
d_max=d.max()
print("d_max=", d_max)
d_min=d.min()
print("d_min=" ,d_min)
d_mean=d.mean()
print("d_mean=" , d_mean)


d_max= 1.9803283169837038
d_min= 1.0543070480391803
d_mean= 1.5232579017788346


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [50]:
# your code here
f=np.empty([2,3,5],dtype=int)
print(f)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [118]:
d

array([[[1.50321267, 1.15958234, 1.95112341, 1.41712892, 1.371625  ],
        [1.09869274, 1.23475594, 1.87357604, 1.05684885, 1.65809426],
        [1.43992422, 1.59552003, 1.16227868, 1.97770196, 1.37988525]],

       [[1.82373042, 1.63296602, 1.28812709, 1.97850435, 1.95257943],
        [1.72461   , 1.98032832, 1.31917599, 1.33005618, 1.30508572],
        [1.66363754, 1.84819495, 1.05430705, 1.24175206, 1.67473159]]])

In [117]:
ind1 = 0
ind2 = 0
ind3 = 0
for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                f[ind1,ind2,ind3]= 25
            if k > d_mean and k < d_max:
                 f[ind1,ind2,ind3]=75
            if k== d_mean:
                 f[ind1,ind2,ind3]=50
            if k== d_min:
                 f[ind1,ind2,ind3]=0
            if k== d_max:
                 f[ind1,ind2,ind3]=100
            ind3 += 1
        ind3=0
        ind2+=1
    ind2=0
    ind1+=1
f

array([[[ 25,  25,  75,  25,  25],
        [ 25,  25,  75,  25,  75],
        [ 25,  75,  25,  75,  25]],

       [[ 75,  75,  25,  75,  75],
        [ 75, 100,  25,  25,  25],
        [ 75,  75,   0,  25,  75]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [124]:
# your code here
ind1 = 0
ind2 = 0
ind3 = 0
for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                f[ind1,ind2,ind3]= "B"
            if k > d_mean and k < d_max:
                 f[ind1,ind2,ind3]="D"
            if k== d_mean:
                 f[ind1,ind2,ind3]="C"
            if k== d_min:
                 f[ind1,ind2,ind3]="A"
            if k== d_max:
                 f[ind1,ind2,ind3]="E"
            ind3 += 1
        ind3=0
        ind2+=1
    ind2=0
    ind1+=1
f

ValueError: setting an array element with a sequence.